### ISSUE TITLE
500, 504, and 505 errors in ERA

### ISSUE THREAD

**Issue by mmstang** [ualbertalib/jupiter#1034]
**Describe the bug**
I have had two separate issues in ERA this morning.
1) When trying to update this record (https://doi.org/10.7939/R3FT8DZ92), I am able to access the edit forms, but get a 505 or a 504 error when trying to save the changes. I have tried editing a test file and got a 500 error.

2) When trying to edit this record (https://era.library.ualberta.ca/items/416a73bb-8106-4c27-ae3e-c3019d43db7e), I immediately get a 500 error when I click on the edit link.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by mmstang** [comment]
A third issue has just come up:
3) I am unable to create collections. Trying to create one results in a 500 error.

**Comment by weiweishi** [comment]
All of the issues are solved with a Fedora restart. 

Debugging steps:
- Identify a 504 Server timeout error when creating/depositing in ERA
- Fedora admin GUI is accessible and read is working
- Any write/post action is timed out on Fedora GUI
- In Fedora log, no error message was shown:
```2019-03-05 10:15:31,158 [http-bio-8080-exec-391] INFO  - FedoraLdp.createObject(517): Ingest with path: /prod/ba/62/e1/f4/ba62e1f4-e7ac-42f0-9ff2-9f2d58b500fb```
- In fcrepo-jcr.log it shows:
```019-03-05 10:32:36,706 [modeshape-event-dispatcher-3-thread-11] ERROR - SLF4JLoggerImpl.error(166): Unexpected error while processing the event 'Save by 'bypassAdmin' at 2019-03-04T15:36:24.466-07:00 with user data = {org.modeshape.jcr.observation.userdata={"baseUrl":"http://mycombe.library.ualberta.ca:8080/fedora/rest/","userAgent":"Faraday v0.12.2"}} in repository with key '32a6fcb' and workspace 'default'```
and it reveals:
```
31 changed 4 nodes:
     32   936198c7505d6492438407-b479-4dfd-9383-2986ac5d5484
     33   936198c7505d643efc6f42-f322-4c97-841c-63a00b09b2e1
     34   936198c7505d648dc705c8-bbf6-4fe3-bd5e-a417aa1c3c82
     35   936198c7505d640fafd244-6f9f-494b-9767-5694ba69ac3a
     36 ' with the sequence number '1028'
     37 java.lang.IllegalAccessError: DB has been closed
     38         at org.mapdb.EngineWrapper.checkClosed(EngineWrapper.java:155)
     39         at org.mapdb.Caches$LRU.get(Caches.java:76)
     40         at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
     41         at org.mapdb.Atomic$Long.get(Atomic.java:315)
     42         at org.modeshape.jcr.index.local.IndexUpdater.writeLatestUpdateTime(IndexUpdater.java:51)
     43         at org.modeshape.jcr.index.local.IndexUpdater.commit(IndexUpdater.java:40)
     44         at org.modeshape.jcr.index.local.LocalIndex.commit(LocalIndex.java:65)
     45         at org.modeshape.jcr.spi.index.provider.IndexChangeAdapter.completeWorkspaceChanges(IndexChangeAdapter.java:104)
     46         at org.modeshape.jcr.cache.change.ChangeSetAdapter.notify(ChangeSetAdapter.java:163)
     47         at org.modeshape.jcr.spi.index.provider.IndexProvider$AtomicIndex.notify(IndexProvider.java:1502)
     48         at org.modeshape.jcr.bus.RepositoryChangeBus$ChangeSetListenerConsumerAdapter.consume(RepositoryChangeBus.java:207)
     49         at org.modeshape.jcr.bus.RepositoryChangeBus$ChangeSetListenerConsumerAdapter.consume(RepositoryChangeBus.java:201)
     50         at org.modeshape.common.collection.ring.RingBuffer$ConsumerRunner.run(RingBuffer.java:466)
     51         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     52         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     53         at java.lang.Thread.run(Thread.java:748)
```
- Connection to PostgreSQL for Fedora has been closed, for some reason - not sure why...

**Comment by mmstang** [comment]
Thanks Weiwei, I am able to edit most records and create collections again,

I am still unable to edit this thesis record: https://doi.org/10.7939/R3J38KS1Q. I immediately get a 500 server error.
